### ISSUE TITLE
order-changes-backwards-2-broadcast-and-wait.sb2 test is flaky

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-vm#1677]
### Expected Behavior
Tests should not be flaky

### Actual Behavior
This test failed 3 out of 4 times on Travis
Tested locally and had 5/5 success rate

```
not ok 12 - ./test/integration/execute.js # time=7807.039ms
 ---
 timeout: 240000
 file: ./test/integration/execute.js
 command: /home/travis/.nvm/versions/node/v10.12.0/bin/node
 args:
   - ./test/integration/execute.js
 stdio:
   - 0
   - pipe
   - 2
 cwd: /home/travis/build/LLK/scratch-vm
 exitCode: 1
 ...

```
The cause is this subtest:

```
order-changes-backwards-2-broadcast-and-wait.sb2
not ok 15 - order-changes-backwards-2-broadcast-and-wait.sb2 # time=102.42ms
     ---
     failures:
       - tapError: incorrect number of tests
     ...
```
